# Generated by Django 2.1.5 on 2019-01-24 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'genus',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=50)),
                ('common_name', models.CharField(max_length=50)),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.Genus')),
            ],
            options={
                'ordering': ('species_name',),
            },
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='uses',
            field=models.ManyToManyField(to='plants.Use'),
        ),
    ]
